application: nextferry
module: default
version: 11
runtime: python27
instance_class: B1
api_version: 1
threadsafe: true
basic_scaling:
   max_instances: 1
   idle_timeout: 15m

handlers:
- url: /tasks/.*
  script: Server.app
  login: admin
- url: /.*
  script: Server.app

inbound_services:
- mail
