runtime: python27
api_version: 1
threadsafe: true

instance_class: B1
basic_scaling:
   max_instances: 1
   idle_timeout: 15m

handlers:
- url: /tasks/.*
  script: Server.app
  login: admin
- url: /.*
  script: Server.app

inbound_services:
- mail
